package lelental.repository;

import lelental.domain.Author;

import java.sql.*;
import java.util.LinkedList;
import java.util.List;

/**
 * @author Paweł Lelental
 **/
public class AuthorRepositoryImpl implements AuthorRepository {

    private Connection connection;
    private PreparedStatement addAuthorStatement;
    private PreparedStatement getAllAuthorsStatement;
    private PreparedStatement deleteAuthor;
    private PreparedStatement findById;
    private PreparedStatement update;

    public AuthorRepositoryImpl(Connection connection) throws SQLException {
        this.connection = connection;
        if (!isDatabaseReady()) {
            populateDb();
        }
        setConnection(connection);
    }

    public AuthorRepositoryImpl() {
    }

    public boolean isDatabaseReady() {
        try {
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Author".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public boolean insert(Author author1) {
        try {
            addAuthorStatement.setString(1, author1.getName());
            addAuthorStatement.setDate(2, new java.sql.Date(author1.getDateOfCreation().getTime()));
            addAuthorStatement.executeUpdate();
            return true;
        } catch (SQLException e) {
            return false;
        }
    }


    @Override
    public boolean update(Author author) throws SQLException {

        try {
            PreparedStatement preparedStatement = update;
            preparedStatement.setString(1, author.getName());
            preparedStatement.setDate(2, new java.sql.Date(author.getDateOfCreation().getTime()));
            preparedStatement.setLong(3, author.getId());
            preparedStatement.executeQuery();
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public Author findById(long id) throws SQLException {
        findById.setLong(1, id);
        ResultSet resultSet = findById.executeQuery();
        Long idFromDb = resultSet.getLong("id");
        String name = resultSet.getString("name");
        Date dateOfCreation = resultSet.getDate("date_of_creation");
        return new Author(idFromDb, name, dateOfCreation);
    }

    @Override
    public List<Author> findAll() throws SQLException {
        List<Author> authorList = new LinkedList<>();
        try {
            ResultSet resultSet = getAllAuthorsStatement.executeQuery();
            while (resultSet.next()) {
                Author author = new Author(resultSet.getLong("id"), resultSet.getString("name"),
                        resultSet.getDate("date_of_creation"));
                authorList.add(author);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
        return authorList;
    }

    @Override
    public boolean delete(long id) throws SQLException {
        try {
            deleteAuthor.setLong(1, id);
            deleteAuthor.executeQuery();
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public String sayWhoYouAre() throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement("SELECT (id,name,date_of_creation) FROM Author WHERE id = 1");
        ResultSet resultSet = preparedStatement.executeQuery();
        Author author = new Author(resultSet.getLong("id"), resultSet.getString("name"), resultSet.getDate("date_of_creation"));
        return "Hello I'm " + author.getName();
    }

    @Override
    public Author findByName(String name) {
        return null;
    }

    @Override
    public void populateDb() throws SQLException {
        connection.createStatement().executeUpdate("CREATE TABLE Author(id BIGINT GENERATED BY DEFAULT AS IDENTITY,name VARCHAR(20) NOT NULL, date_of_creation DATE NOT NULL)");
    }

    @Override
    public void dropAuthorTable() throws SQLException {
        connection.createStatement().executeUpdate("DROP TABLE Author");
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        addAuthorStatement = connection.
                prepareStatement
                        ("INSERT INTO Author (name, date_of_creation) VALUES (?, ?)");
        getAllAuthorsStatement = connection.
                prepareStatement("SELECT id, name, date_of_creation FROM Author");
        deleteAuthor = connection.prepareStatement("DELETE FROM Author WHERE id = ?");
        findById = connection.prepareStatement("SELECT id,name,date_of_creation FROM Author WHERE id = ?");
        update = connection.prepareStatement("UPDATE Author SET name = ?, date_of_creation = ? WHERE id= ? ");
    }


}
